### ISSUE TITLE
how to defind umi locate

### ISSUE THREAD

**Issue by huangl07** [weng-lab/umitools#4]
dear support

I am using the umitools for some RNA-sequence，it was using NEXTflex™ qRNA-SEQ™ RNA SAMPLE PREPARATION PROTOCOL

How to defind the umi parameters？

thankyou！

**Comment by yfu** [comment]
Sorry for the late reply! You can take a quick look at [Figure 1](https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-018-4933-1/figures/1) in [our paper](https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-018-4933-1). `umitools` was specifically designed to handled UMI sequences from the protocols described in this paper.
