### ISSUE TITLE
how may use umitools for RNAseq when it present on read1 but on both end?

### ISSUE THREAD

**Issue by unique379r** [weng-lab/umitools#6]
I am currently seeking assistance in accurately identifying genuine PCR duplicates and unique molecular identifiers (UMI) within my RNA sequencing samples. I am aware that the RNAseq data we have acquired includes 5' and 3' UMIs within Read 1.

Could you kindly provide guidance on the appropriate approach to address this issue? Specifically, what should I specify parameters to account for both the 5' and 3' UMI?

![Screenshot 2023-10-19 at 12 16 01 PM](https://github.com/weng-lab/umitools/assets/41694905/f10288a6-0793-485d-a64f-7d2af2fe97ba)

**Comment by yfu** [comment]
Hi @unique379r! Thanks for your question. I don't think `umitools` was designed to be flexible enough to handle all kinds of UMI locations. Unfortunately, I no longer work on this project, but it might be worth a try to see if https://github.com/CGATOxford/UMI-tools works for you.

**Comment by yfu** [comment]
Closing this issue for now. Good luck with your research project!
